name = "discordluau/voice"
description = "This package is responsible for implementing voice support in DiscordLuau. One of the difficulties of this package will be overcoming the 64 bit encrypted voice packets that are sent by Discord."
version = "0.0.1"

[target]
environment = "lune"